# Path to oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Update behaviour configuration
zstyle ':omz:update' mode reminder  # just remind me to update when it's time
# How often to auto-update (in days).
zstyle ':omz:update' frequency 13

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# The following line if you want to changes the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
HIST_STAMPS="mm/dd/yyyy"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  asdf
)

source $ZSH/oh-my-zsh.sh

# User configuration

## ENV VARS

export PATH="$HOME/.cargo/bin:$PATH"

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='code'
fi
export GIT_EDITOR=vim
export BUNDLER_EDITOR=code

export DISABLE_SPRING=1
export RDBG_FRONTEND='vscode'
export RUBY_CONFIGURE_OPTS=--enable-yjit

# Override MacOS provided icu4c with Homebrew one because it doesn't provide everything
export PATH="/usr/local/opt/icu4c/bin:/usr/local/opt/icu4c/sbin:$PATH"

## ALIASES

alias zshconfig="code ~/.zshrc"
alias ohmyzsh="code $ZSH"

alias be="bundle exec"


